version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always
    depends_on:
      - userservice
      - paymentservice
    networks:
      - simplebank_network
  userservice:
    build:  
      context: ./user
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:8081
    networks:
      - simplebank_network
    env_file:
      - .env
  paymentservice:
    build: 
      context: ./payment
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8082:8082
    networks:
      - simplebank_network
    env_file:
      - .env

networks:
  simplebank_network:

volumes:
  simplebank_volume: